# Generated by Django 5.2.6 on 2025-10-04 02:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Mantenimiento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('estimated_duration', models.DurationField(verbose_name='Duración Estimada')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('vehicle_type', models.CharField(choices=[('car', 'Automóvil'), ('truck', 'Camión'), ('motorcycle', 'Motocicleta'), ('bus', 'Autobús'), ('van', 'Van')], max_length=20, verbose_name='Tipo de Vehículo')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasolina'), ('diesel', 'Diésel'), ('electric', 'Eléctrico'), ('hybrid', 'Híbrido'), ('lpg', 'GLP')], max_length=20, verbose_name='Tipo de Combustible')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Nombre del Propietario')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('owner_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Fecha Programada')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantencion.maintenancetype', verbose_name='Tipo de Mantenimiento')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantencion.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Pregunta de Evaluación')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantencion.maintenance', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name': 'Evaluación de Servicio',
                'verbose_name_plural': 'Evaluaciones de Servicios',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Opción de Evaluación')),
                ('votes', models.IntegerField(default=0, verbose_name='Votos')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantencion.serviceevaluation', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Opción de Evaluación',
                'verbose_name_plural': 'Opciones de Evaluación',
            },
        ),
    ]
